level_map=[
'                     f  f                             ',
'                      ff                              ',
'           s          ff                              ',
'          sss        f  f xx     ss                    ',
'         sssss      f    f      ssss                  ',
'                   f      ff                           ',
'                  f         f                         ',
'                             f                        ',
'                    xx                                ',
'      ii           xxx             iii                ',
'      ii          xxxx             iii                ',
'xxx              xxxxx             iii     x x        ',
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ',
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ',
]
tiles = {
    'o': './assets/black.png',
    'u': './assets/tile.png',
    'v': './assets/topTile.png',
    'w': './assets/topTileLeftCorner.png',
    'x': './assets/topTileRightCorner.png',
    'y': './assets/bottomTileRightCorner.png',
    'z': './assets/bottomTileLeftCorner.png',
    'q': './assets/topTileLilCornerBottomLeft.png',
    'r': './assets/topTileLilCornerBottomRight.png',
    's': './assets/topTileLilCornerTopRight.png',
    't': './assets/topTileLilCornerTopLeft.png',
    'p': './assets/leftTile.png',
    'n': './assets/tileRight.png',
    'm': './assets/bottomTile.png',
    'l': './assets/AcidTop.png',
    'k': './assets/AcidTopTile.png',
    'j': './assets/AcidCorner_rechts_oben.png',
    'i': './assets/AcidtopTileLeftBottomCorner.png',
    'h': './assets/AcidtopTileLeftCorner.png',
    'g': './assets/AcidtopTileRightBottomCorner.png',
    'f': './assets/yellow.png'

}
tilsize = 64