level_map=[
'                           ',
'                           ',
'                           ',
'    wvvvx                  ',
'    immmy                  ',
'                           ',
'                           ',
'           wj              ',
'           zy          wvx ',
'                     wvtun ',
'                   wvtuuun ',
' wx           wvkvvtuuuuun ',
'vtsvx  wvkkkvvtuuuuuuuuuun ',
'uuuun  puuuuuuuuuuuuuuuuun ',
]
tiles = {
    'o': './assets/black.png',
    'u': './assets/tile.png',
    'v': './assets/topTile.png',
    'w': './assets/topTileLeftCorner.png',
    'x': './assets/topTileRightCorner.png',
    'y': './assets/bottomTileRightCorner.png',
    'z': './assets/bottomTileLeftCorner.png',
    'q': './assets/topTileLilCornerBottomLeft.png',
    'r': './assets/topTileLilCornerBottomRight.png',
    's': './assets/topTileLilCornerTopRight.png',
    't': './assets/topTileLilCornerTopLeft.png',
    'p': './assets/leftTile.png',
    'n': './assets/tileRight.png',
    'm': './assets/bottomTile.png',
    'l': './assets/AcidTop.png',
    'k': './assets/AcidTopTile.png',
    'j': './assets/AcidCorner_rechts_oben.png',
    'i': './assets/AcidtopTileLeftBottomCorner.png',
    'h': './assets/AcidtopTileLeftCorner.png',
    'g': './assets/AcidtopTileRightBottomCorner.png',
    'f': './assets/yellow.png'

}
tilsize = 64